package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GAME_INFO.
 */
public class GameInfo {

    private Long id;
    private String name;
    private Long gameid;
    private String tips;
    private String playerSource;
    private Long upTime;
    private String others;
    private String introuduction;
    private String imageUrl;
    private String upDescription;
    private String companyGameId;
    private String comment;

    public GameInfo() {
    }

    public GameInfo(Long id) {
        this.id = id;
    }

    public GameInfo(Long id, String name, Long gameid, String tips, String playerSource, Long upTime, String others, String introuduction, String imageUrl, String upDescription, String companyGameId, String comment) {
        this.id = id;
        this.name = name;
        this.gameid = gameid;
        this.tips = tips;
        this.playerSource = playerSource;
        this.upTime = upTime;
        this.others = others;
        this.introuduction = introuduction;
        this.imageUrl = imageUrl;
        this.upDescription = upDescription;
        this.companyGameId = companyGameId;
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getGameid() {
        return gameid;
    }

    public void setGameid(Long gameid) {
        this.gameid = gameid;
    }

    public String getTips() {
        return tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

    public String getPlayerSource() {
        return playerSource;
    }

    public void setPlayerSource(String playerSource) {
        this.playerSource = playerSource;
    }

    public Long getUpTime() {
        return upTime;
    }

    public void setUpTime(Long upTime) {
        this.upTime = upTime;
    }

    public String getOthers() {
        return others;
    }

    public void setOthers(String others) {
        this.others = others;
    }

    public String getIntrouduction() {
        return introuduction;
    }

    public void setIntrouduction(String introuduction) {
        this.introuduction = introuduction;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUpDescription() {
        return upDescription;
    }

    public void setUpDescription(String upDescription) {
        this.upDescription = upDescription;
    }

    public String getCompanyGameId() {
        return companyGameId;
    }

    public void setCompanyGameId(String companyGameId) {
        this.companyGameId = companyGameId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
