package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GAME_INFO.
 */
public class GameInfo {

    private Long id;
    private String sort;
    private String game_id;
    private String require;
    private String game_img;
    private String game_download_nums;
    private String game_platform;
    private String game_stage;
    private String game_name;
    private String game_download_url;
    private String game_size;
    private String norms;
    private String game_grade;
    private String game_type;

    public GameInfo() {
    }

    public GameInfo(Long id) {
        this.id = id;
    }

    public GameInfo(Long id, String sort, String game_id, String require, String game_img, String game_download_nums, String game_platform, String game_stage, String game_name, String game_download_url, String game_size, String norms, String game_grade, String game_type) {
        this.id = id;
        this.sort = sort;
        this.game_id = game_id;
        this.require = require;
        this.game_img = game_img;
        this.game_download_nums = game_download_nums;
        this.game_platform = game_platform;
        this.game_stage = game_stage;
        this.game_name = game_name;
        this.game_download_url = game_download_url;
        this.game_size = game_size;
        this.norms = norms;
        this.game_grade = game_grade;
        this.game_type = game_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getGame_id() {
        return game_id;
    }

    public void setGame_id(String game_id) {
        this.game_id = game_id;
    }

    public String getRequire() {
        return require;
    }

    public void setRequire(String require) {
        this.require = require;
    }

    public String getGame_img() {
        return game_img;
    }

    public void setGame_img(String game_img) {
        this.game_img = game_img;
    }

    public String getGame_download_nums() {
        return game_download_nums;
    }

    public void setGame_download_nums(String game_download_nums) {
        this.game_download_nums = game_download_nums;
    }

    public String getGame_platform() {
        return game_platform;
    }

    public void setGame_platform(String game_platform) {
        this.game_platform = game_platform;
    }

    public String getGame_stage() {
        return game_stage;
    }

    public void setGame_stage(String game_stage) {
        this.game_stage = game_stage;
    }

    public String getGame_name() {
        return game_name;
    }

    public void setGame_name(String game_name) {
        this.game_name = game_name;
    }

    public String getGame_download_url() {
        return game_download_url;
    }

    public void setGame_download_url(String game_download_url) {
        this.game_download_url = game_download_url;
    }

    public String getGame_size() {
        return game_size;
    }

    public void setGame_size(String game_size) {
        this.game_size = game_size;
    }

    public String getNorms() {
        return norms;
    }

    public void setNorms(String norms) {
        this.norms = norms;
    }

    public String getGame_grade() {
        return game_grade;
    }

    public void setGame_grade(String game_grade) {
        this.game_grade = game_grade;
    }

    public String getGame_type() {
        return game_type;
    }

    public void setGame_type(String game_type) {
        this.game_type = game_type;
    }

}
